spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/incident_management
    username: root
    password: C_20051685
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
